include: package:lints/recommended.yaml
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
linter:
  rules:
    avoid_dynamic_calls: true
    avoid_final_parameters: true
    avoid_print: false
    avoid_unused_constructor_parameters: true
    camel_case_types: true
    combinators_ordering: true
    comment_references: true
    dangling_library_doc_comments: false
    invalid_case_patterns: true
    no_self_assignments: true
    no_wildcard_variable_uses: true
    omit_local_variable_types: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_expression_function_bodies: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    unnecessary_await_in_return: true
    unnecessary_breaks: true
    unnecessary_lambdas: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_null_checks: true
    unnecessary_parenthesis: true
    unnecessary_statements: true