/**
 * Problem 2: Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */
library problem_002;

void main() {
  var max = 4000000;

  var s = 0;
  var a = 1, b = 0;
  while (true) {
    var c = a + b;
    if (c > max) {
      print(s);
      return;
    }
    if (c % 2 == 0) {
      s += c;
    }
    a = b;
    b = c;
  }
}
