name: euler
version: 0.0.11

description: My advances on Project Euler.
homepage: https://github.com/renggli/dart-euler

environment:
  sdk: ^3.2.0
dependencies:
  collection: ^1.18.0
  data: ^0.12.0
  meta: ^1.9.0
  more: ^4.0.0
  petitparser: ^6.0.0
  test: ^1.24.0
dev_dependencies:
  lints: ^3.0.0
