name: euler
version: 0.0.9

description: My advances on Project Euler.
homepage: https://github.com/renggli/dart-euler

environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  collection: ^1.16.0
  data: ^0.10.0
  lints: ^2.0.0
  meta: ^1.8.0
  more: ^3.8.0
  petitparser: ^5.0.0
  test: ^1.21.0
