name: euler
version: 0.0.12

description: My advances on Project Euler.
homepage: https://github.com/renggli/dart-euler

environment:
  sdk: ^3.8.0
dependencies:
  args: ^2.7.0
  bcrypt: ^1.1.0
  bits: ^1.4.0
  characters: ^1.4.0
  charset: ^2.0.0
  collection: ^1.19.0
  data: ^0.15.0
  meta: ^1.17.0
  more: ^4.6.0
  petitparser: ^7.0.0
  test: ^1.26.0
  timezone: ^0.10.0
  z3: ^0.1.0
dev_dependencies:
  lints: ^6.0.0
