name: euler
version: 0.0.11

description: My advances on Project Euler.
homepage: https://github.com/renggli/dart-euler

environment:
  sdk: ^3.5.0
dependencies:
  collection: ^1.19.0
  data: ^0.13.0
  meta: ^1.16.0
  more: ^4.3.0
  petitparser: ^6.0.0
  test: ^1.25.0
  z3: ^0.1.0
dev_dependencies:
  lints: ^5.0.0
