name: euler
version: 0.0.10

description: My advances on Project Euler.
homepage: https://github.com/renggli/dart-euler

environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  collection: ^1.17.0
  data: ^0.11.0
  meta: ^1.9.0
  more: ^3.10.0
  petitparser: ^5.3.0
  test: ^1.24.0
dev_dependencies:
  lints: ^2.0.0