name: euler
version: 0.0.8

description: My advances on Project Euler.
homepage: https://github.com/renggli/dart-euler

environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  data: ^0.7.0
  lints: ^1.0.0
  more: ^3.3.0
  petitparser: ^4.3.0
  test: ^1.17.0
