/**
 * Problem 45: Triangular, pentagonal, and hexagonal
 *
 * Triangle, pentagonal, and hexagonal numbers are generated by the following
 * formulae:
 *
 * Triangle      T_n = n * (n + 1) / 2       1, 3, 6, 10, 15, ...
 * Pentagonal    P_n = n * (3 * n - 1) / 2   1, 5, 12, 22, 35, ...
 * Hexagonal     H_n = n * (2 * n - 1)       1, 6, 15, 28, 45, ...
 *
 * It can be verified that T285 = P165 = H143 = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 */
library problem_045;

import 'dart:math';
import 'package:more/bit_set.dart';
import 'package:more/int_math.dart';
import 'package:more/iterable.dart';
import 'package:more/range.dart';

void main() {
  assert(false);
}